rabbitmq:
  image: rabbitmq:3.5.4
  container_name: rabbitplaymq
  hostname: rabbitmq
  environment:
    RABBITMQ_NODENAME: touchbank
    RABBITMQ_ERLANG_COOKIE: tb_cookie
    RABBITMQ_DEFAULT_VHOST: rabbit_host
    RABBITMQ_DEFAULT_USER: rabbit_user
    RABBITMQ_DEFAULT_PASS: rabbit_password
