rabbitmq:
  image: rabbitmq:3.5.6-management
  ports:
    - "5672:5672"
    - "15672:15672"
  hostname: rabbitmq
  environment:
    RABBITMQ_NODENAME: swipe_rabbit
    RABBITMQ_ERLANG_COOKIE: swipe_cookie
